ebook_metadata:
  title: ༄༅། །བཀའ་བརྒྱད་རྣམ་བཤད། །
  authors:
  - མཛད་པ་པོ། འཇམ་མགོན་མི་ཕམ།
  sku: SHE-002
  layers:
  - book_title
  - author
  - chapter_title
  - quotation
  - sabche
web_metadata:
  title:
    en: A Presentation of the Eight Herukas
    bo: བཀའ་བརྒྱད་རྣམ་བཤད།
  collection:
    en: Shechen Tantra Series–  Book 2
    bo: ''
  author:
    en: Jamgon Mipham Gyatso
    bo: འཇམ་མགོན་མི་ཕམ་རྒྱ་མཚོ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-002
  category:
    en: Uncategorized
    bo: Uncategorized @tib
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-002.epub
  description:
    en: ''
    bo: ''
